apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-dupa2
  labels:
    app: my-app-dupa2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-dupa2
  template:
    metadata:
      labels:
        app: my-app-dupa2
    spec:
      containers:
      - name: my-app-dupa2
        image: nginx:latest
        ports:
        - containerPort: 80
